import { hashPassword } from './password';

export const getInitialData = async () => {
  const defaultPasswordHash = await hashPassword('AdminPassword123!');

  return {
    adminUser: {
      id: 'usr_admin_001',
      name: 'Debkanta Dey',
      email: 'admin@alexmorgan.dev',
      passwordHash: defaultPasswordHash,
      role: 'ADMIN',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=500&q=80',
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date(),
    },
    profile: {
      id: 'prof_001',
      fullName: 'Debkanta Dey',
      professionalTitle: 'Senior Full-Stack Engineer & Cloud Architect',
      shortBio: 'Engineering high-performance web platforms, resilient distributed backends, and modern developer tooling.',
      longBio: 'With over 7 years of full-stack engineering expertise, I specialize in crafting robust, scalable digital platforms using Next.js, TypeScript, Node.js, and PostgreSQL. I have architected systems processing millions of daily transactions, led multi-disciplinary agile teams, and built intuitive user interfaces with clean architecture and meticulous attention to UX.',
      profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
      location: 'San Francisco, CA (Open to Worldwide Remote)',
      email: 'alex@alexmorgan.dev',
      phone: '+1 (415) 890-4211',
      availabilityStatus: 'Open to Full-Time Staff/Senior Roles & Consulting',
      yearsOfExperience: 7,
      resumeUrl: '/uploads/Alex_Morgan_Resume.pdf',
      githubUrl: 'https://github.com',
      linkedinUrl: 'https://linkedin.com',
      portfolioUrl: 'https://alexmorgan.dev',
      websiteUrl: 'https://alexmorgan.dev',
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date(),
    },
    statistics: [
      { id: 'stat_1', label: 'Years of Experience', value: '7+', icon: 'Briefcase', displayOrder: 1 },
      { id: 'stat_2', label: 'Production Projects Delivered', value: '45+', icon: 'Code', displayOrder: 2 },
      { id: 'stat_3', label: 'Technologies & Frameworks', value: '25+', icon: 'Layers', displayOrder: 3 },
      { id: 'stat_4', label: 'Enterprise Uptime SLA', value: '99.98%', icon: 'ShieldCheck', displayOrder: 4 },
    ],
    skills: [
      { id: 'sk_1', name: 'React', category: 'Frontend', proficiency: 96, icon: 'React', description: 'Advanced component composition, custom hooks, fiber architecture', displayOrder: 1, featured: true, isActive: true },
      { id: 'sk_2', name: 'Next.js', category: 'Frontend', proficiency: 94, icon: 'Globe', description: 'App Router, SSR, SSG, Server Actions, Streaming', displayOrder: 2, featured: true, isActive: true },
      { id: 'sk_3', name: 'TypeScript', category: 'Frontend', proficiency: 95, icon: 'Code', description: 'Strict type safety, generics, AST, advanced type utilities', displayOrder: 3, featured: true, isActive: true },
      { id: 'sk_4', name: 'Tailwind CSS', category: 'Frontend', proficiency: 92, icon: 'Palette', description: 'Design systems, modern fluid typography, dark mode', displayOrder: 4, featured: true, isActive: true },
      { id: 'sk_5', name: 'Node.js', category: 'Backend', proficiency: 94, icon: 'Server', description: 'Event loop performance tuning, streams, worker threads', displayOrder: 5, featured: true, isActive: true },
      { id: 'sk_6', name: 'Express.js', category: 'Backend', proficiency: 92, icon: 'Cpu', description: 'Production REST APIs, middleware chains, security hardening', displayOrder: 6, featured: true, isActive: true },
      { id: 'sk_7', name: 'PostgreSQL', category: 'Database', proficiency: 90, icon: 'Database', description: 'Query tuning, indexing strategies, transactions, EXPLAIN ANALYZE', displayOrder: 7, featured: true, isActive: true },
      { id: 'sk_8', name: 'Prisma ORM', category: 'Database', proficiency: 92, icon: 'Layers', description: 'Schema migrations, type-safe queries, relation mapping', displayOrder: 8, featured: true, isActive: true },
      { id: 'sk_9', name: 'Docker', category: 'DevOps / Cloud', proficiency: 88, icon: 'Box', description: 'Multi-stage builds, orchestration, environment parity', displayOrder: 9, featured: true, isActive: true },
      { id: 'sk_10', name: 'Kubernetes & AWS', category: 'DevOps / Cloud', proficiency: 84, icon: 'Cloud', description: 'EKS, ECS, S3, CloudFront, IAM security policies', displayOrder: 10, featured: true, isActive: true },
      { id: 'sk_11', name: 'GraphQL & WebSockets', category: 'Backend', proficiency: 86, icon: 'Zap', description: 'Real-time pub/sub, subscriptions, bi-directional streaming', displayOrder: 11, featured: false, isActive: true },
      { id: 'sk_12', name: 'React Native', category: 'Mobile', proficiency: 82, icon: 'Smartphone', description: 'Cross-platform mobile applications for iOS and Android', displayOrder: 12, featured: false, isActive: true },
      { id: 'sk_13', name: 'Redis Cache', category: 'Database', proficiency: 88, icon: 'Zap', description: 'In-memory caching, rate limiting, distributed locking', displayOrder: 13, featured: false, isActive: true },
      { id: 'sk_14', name: 'CI/CD & GitHub Actions', category: 'DevOps / Cloud', proficiency: 90, icon: 'GitBranch', description: 'Automated test suites, security scans, zero-downtime deploys', displayOrder: 14, featured: true, isActive: true },
    ],
    experiences: [
      {
        id: 'exp_1',
        companyName: 'CloudScale Technologies',
        companyLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=120&q=80',
        companyWebsite: 'https://cloudscale.example.com',
        jobTitle: 'Lead Full-Stack Engineer',
        employmentType: 'Full-time',
        location: 'San Francisco, CA (Hybrid)',
        startDate: new Date('2022-03-01'),
        endDate: null,
        currentlyWorking: true,
        description: 'Directing the architecture and implementation of the enterprise cloud monitoring and observability platform used by over 300+ enterprise clients.',
        responsibilities: [
          'Architected and delivered low-latency telemetry analytics engine processing 40M+ events daily with Next.js App Router and Node.js microservices.',
          'Mentored a cross-functional team of 8 full-stack engineers, instituting code review standards and 95%+ unit/integration test coverage.',
          'Spearheaded migration to Docker containerized microservices on AWS, reducing mean deployment time by 65%.',
          'Championed accessibility (WCAG 2.1 AA) and Core Web Vitals across all public-facing dashboard applications.'
        ],
        achievements: [
          'Reduced 95th-percentile API response latency from 420ms to 78ms using Redis multi-tier caching.',
          'Awarded Engineering Excellence Award Q4 2023 for leading zero-downtime database migration.'
        ],
        technologiesUsed: ['Next.js', 'React', 'TypeScript', 'Node.js', 'PostgreSQL', 'Docker', 'AWS', 'Redis', 'Tailwind CSS'],
        displayOrder: 1,
        isFeatured: true,
        createdAt: new Date('2022-03-01'),
        updatedAt: new Date(),
      },
      {
        id: 'exp_2',
        companyName: 'Apex FinTech Systems',
        companyLogo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=120&q=80',
        companyWebsite: 'https://apexfintech.example.com',
        jobTitle: 'Senior Software Engineer',
        employmentType: 'Full-time',
        location: 'New York, NY (Remote)',
        startDate: new Date('2020-01-15'),
        endDate: new Date('2022-02-28'),
        currentlyWorking: false,
        description: 'Engineered high-throughput financial transaction ledger and merchant payment gateway APIs.',
        responsibilities: [
          'Developed idempotent payment processing services handling $15M+ in weekly transaction volume.',
          'Constructed responsive merchant analytics portal with real-time settlement tracking and PDF statement generation.',
          'Implemented end-to-end cryptographic hashing, JWT security middleware, and role-based permissions.'
        ],
        achievements: [
          'Eliminated double-spend transaction anomalies through distributed database locks.',
          'Automated PCI-DSS compliance audits, cutting manual verification hours by 80%.'
        ],
        technologiesUsed: ['Node.js', 'Express.js', 'TypeScript', 'PostgreSQL', 'Prisma', 'React', 'Docker'],
        displayOrder: 2,
        isFeatured: true,
        createdAt: new Date('2020-01-15'),
        updatedAt: new Date(),
      },
      {
        id: 'exp_3',
        companyName: 'Nova Interactive Labs',
        companyLogo: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=120&q=80',
        companyWebsite: 'https://novalabs.example.com',
        jobTitle: 'Full-Stack Developer',
        employmentType: 'Full-time',
        location: 'Austin, TX',
        startDate: new Date('2018-06-01'),
        endDate: new Date('2019-12-31'),
        currentlyWorking: false,
        description: 'Built custom client web applications, RESTful microservices, and interactive data visualization dashboards.',
        responsibilities: [
          'Engineered full-stack single-page applications for 15+ external enterprise clients.',
          'Created reusable React component libraries and design tokens adopted company-wide.',
          'Implemented automated CI/CD deployment pipelines using GitHub Actions.'
        ],
        achievements: [
          'Delivered all 15 customer milestones on-time with zero critical production bugs.',
          'Maintained client satisfaction score of 4.9/5.0.'
        ],
        technologiesUsed: ['React', 'JavaScript', 'Node.js', 'Express', 'PostgreSQL', 'CSS3', 'REST APIs'],
        displayOrder: 3,
        isFeatured: false,
        createdAt: new Date('2018-06-01'),
        updatedAt: new Date(),
      }
    ],
    educations: [
      {
        id: 'edu_1',
        institution: 'University of California, Berkeley',
        institutionLogo: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=120&q=80',
        degree: 'Bachelor of Science (B.S.)',
        fieldOfStudy: 'Computer Science & Software Systems',
        location: 'Berkeley, CA',
        startDate: new Date('2014-08-20'),
        endDate: new Date('2018-05-15'),
        currentlyStudying: false,
        description: 'Rigorous computer science curriculum with strong focus on algorithms, distributed databases, cloud systems, and compiler design.',
        achievements: [
          'Graduated Magna Cum Laude (GPA: 3.89 / 4.00)',
          'President of the Association for Computing Machinery (ACM) Student Chapter',
          'First Place - UC Berkeley Annual Hackathon 2017'
        ],
        grade: '3.89 / 4.00',
        website: 'https://berkeley.edu',
        displayOrder: 1,
        createdAt: new Date('2014-08-20'),
        updatedAt: new Date(),
      }
    ],
    projects: [
      {
        id: 'proj_1',
        title: 'OmniPulse - Cloud Observability & Infrastructure Monitor',
        slug: 'omnipulse-cloud-observability',
        shortDescription: 'Enterprise real-time cloud infrastructure monitoring platform with anomaly detection, live metrics telemetry, and incident alerting.',
        fullDescription: 'OmniPulse is an end-to-end cloud observability suite designed for modern engineering teams. It aggregates logs, metrics, and distributed tracing data across Kubernetes clusters and serverless functions into a single unified pane of glass. Featuring millisecond live streaming via WebSockets, intelligent anomaly alerts, and customizable dashboard widgets, OmniPulse empowers DevOps teams to detect and resolve critical regressions before customers are impacted.',
        featuredImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
        galleryImages: [
          'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?auto=format&fit=crop&w=1000&q=80',
          'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1000&q=80'
        ],
        technologies: ['Next.js 15', 'TypeScript', 'Node.js', 'PostgreSQL', 'Prisma', 'Docker', 'Redis', 'Tailwind CSS'],
        category: 'SaaS',
        projectType: 'SaaS',
        liveUrl: 'https://example.com/demo/omnipulse',
        githubUrl: 'https://github.com/example/omnipulse',
        caseStudyUrl: '/projects/omnipulse-cloud-observability',
        startDate: new Date('2023-04-01'),
        endDate: new Date('2023-11-30'),
        status: 'Completed',
        challenges: 'Handling concurrent ingestion bursts of 50,000+ metric points per second without incurring high cloud computing overhead or database write contention.',
        solutions: 'Architected an in-memory aggregation buffer using Redis Streams and TimescaleDB hypertable partitioning, backed by a resilient worker pool that batches database operations.',
        keyFeatures: [
          'Real-time streaming dashboard with interactive time-series zoom and crosshair tracking',
          'Automated threshold and statistical anomaly alerting via Webhooks and Slack integration',
          'Comprehensive role-based access control (RBAC) with audit logs',
          'Lightweight Node.js agent SDK with sub-millisecond CPU footprint'
        ],
        responsibilities: 'Principal Architect & Lead Full-Stack Developer: Designed relational database schemas, built REST and WebSocket endpoints, and engineered responsive frontend charts.',
        displayOrder: 1,
        featured: true,
        published: true,
        createdAt: new Date('2023-04-01'),
        updatedAt: new Date(),
      },
      {
        id: 'proj_2',
        title: 'AuraFlow - AI-Powered Collaborative Workspace',
        slug: 'auraflow-ai-workspace',
        shortDescription: 'Modern collaborative workspace combining document editing, interactive canvas diagrams, and generative AI research assistance.',
        fullDescription: 'AuraFlow is a modern productivity tool that brings together distributed teams. It provides a fluid rich-text editor with multi-cursor collaboration, vector graphic brainstorming canvas, and context-aware AI copilots that summarize meeting transcripts and auto-generate project task breakdowns.',
        featuredImage: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=80',
        galleryImages: [
          'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=1000&q=80'
        ],
        technologies: ['React', 'Next.js', 'TypeScript', 'Node.js', 'PostgreSQL', 'WebSockets', 'Tailwind CSS'],
        category: 'Web Application',
        projectType: 'Web Application',
        liveUrl: 'https://example.com/demo/auraflow',
        githubUrl: 'https://github.com/example/auraflow',
        caseStudyUrl: '/projects/auraflow-ai-workspace',
        startDate: new Date('2023-12-01'),
        endDate: new Date('2024-05-15'),
        status: 'Completed',
        challenges: 'Achieving sub-50ms conflict resolution for concurrent character-by-character real-time collaborative typing across multiple geographic regions.',
        solutions: 'Implemented CRDT (Conflict-free Replicated Data Types) synchronized over WebSocket transport with optimistic local state rendering and reconciliation.',
        keyFeatures: [
          'Zero-latency real-time multi-user cursor tracking and rich document editing',
          'Integrated AI assistants for instant summarization, translation, and code formatting',
          'Interactive infinite whiteboard canvas with shape auto-align and image exports',
          'End-to-end encrypted team spaces with granular document permissions'
        ],
        responsibilities: 'Full-Stack Developer: Developed collaborative synchronization layer, UI components, and integrated backend API authentication.',
        displayOrder: 2,
        featured: true,
        published: true,
        createdAt: new Date('2023-12-01'),
        updatedAt: new Date(),
      },
      {
        id: 'proj_3',
        title: 'NovaPay - Multi-Currency Merchant Ledger & Gateway',
        slug: 'novapay-merchant-gateway',
        shortDescription: 'Robust financial ledger and payment orchestrator facilitating automated multi-currency cross-border settlements.',
        fullDescription: 'NovaPay provides enterprise merchants with a mission-critical financial backend. Built on strict double-entry bookkeeping principles, NovaPay handles multi-currency transactions, currency conversions, fraud heuristics, and automated recurring billing with complete auditability.',
        featuredImage: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=1200&q=80',
        galleryImages: [
          'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1000&q=80'
        ],
        technologies: ['Node.js', 'Express.js', 'TypeScript', 'PostgreSQL', 'Prisma', 'Docker', 'Jest'],
        category: 'FinTech',
        projectType: 'API',
        liveUrl: 'https://example.com/demo/novapay',
        githubUrl: 'https://github.com/example/novapay',
        caseStudyUrl: '/projects/novapay-merchant-gateway',
        startDate: new Date('2022-06-01'),
        endDate: new Date('2023-02-28'),
        status: 'Completed',
        challenges: 'Preventing race conditions during balance deductions and meeting strict zero-financial-drift regulatory audits.',
        solutions: 'Enforced PostgreSQL SERIALIZABLE transaction isolation levels combined with ledger journal immutability and cryptographically signed balance receipts.',
        keyFeatures: [
          'Double-entry accounting engine guaranteeing zero ledger imbalances',
          'Support for 35+ global fiat currencies with dynamic mid-market FX rates',
          'Automated webhook dispatcher with exponential backoff and replay defense',
          'High-security API keys with scope limitations and IP whitelisting'
        ],
        responsibilities: 'Backend Architect: Authored all database migrations, transaction concurrency tests, and PCI-compliant Express middleware.',
        displayOrder: 3,
        featured: true,
        published: true,
        createdAt: new Date('2022-06-01'),
        updatedAt: new Date(),
      },
      {
        id: 'proj_4',
        title: 'DevSphere - Engineering Intelligence & Knowledge Graph',
        slug: 'devsphere-knowledge-graph',
        shortDescription: 'Developer tooling platform that indexes codebase architectures, dependency vulnerabilities, and API documentation.',
        fullDescription: 'DevSphere connects code repositories, cloud infrastructure topologies, and engineering documentation into an interactive graph. Engineers can query system dependencies, track breaking API changes across microservices, and onboard to new repositories in minutes.',
        featuredImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80',
        galleryImages: [],
        technologies: ['Next.js', 'TypeScript', 'Node.js', 'PostgreSQL', 'Tailwind CSS'],
        category: 'Developer Tools',
        projectType: 'Web Application',
        liveUrl: 'https://example.com/demo/devsphere',
        githubUrl: 'https://github.com/example/devsphere',
        caseStudyUrl: '/projects/devsphere-knowledge-graph',
        startDate: new Date('2024-01-10'),
        endDate: null,
        status: 'In Progress',
        challenges: 'Parsing and linking abstract syntax trees across multi-language monorepos with hundreds of thousands of files.',
        solutions: 'Created streaming worker pipelines that generate localized dependency graphs and index AST nodes into indexed PostgreSQL relational structures.',
        keyFeatures: [
          'Interactive 3D dependency visualizer with service-to-service call traces',
          'Automated OpenAPI specification generation from codebase routes',
          'Smart semantic search across pull requests and documentation',
          'Continuous drift warning when production routes deviate from schema'
        ],
        responsibilities: 'Lead Full-Stack Developer: Engineered the UI visualization canvas, graph queries, and Next.js frontend pages.',
        displayOrder: 4,
        featured: false,
        published: true,
        createdAt: new Date('2024-01-10'),
        updatedAt: new Date(),
      }
    ],
    services: [
      {
        id: 'srv_1',
        title: 'Full-Stack Web Application Development',
        slug: 'full-stack-web-development',
        icon: 'Layers',
        shortDescription: 'Turnkey development of end-to-end modern web applications built for speed, reliability, and scale.',
        fullDescription: 'From architectural discovery to deployment, I build robust, production-grade applications using Next.js, React, Node.js, and PostgreSQL. Every solution is delivered with type safety, clean code architecture, comprehensive automated tests, and accessible responsive interfaces.',
        features: [
          'Complete frontend and backend architecture tailored to your business needs',
          'End-to-end TypeScript implementation ensuring minimal runtime issues',
          'Relational database design and migration management with Prisma',
          'Clean RESTful or GraphQL API engineering with full documentation'
        ],
        technologies: ['Next.js', 'React', 'Node.js', 'Express', 'PostgreSQL', 'Prisma', 'TypeScript'],
        displayOrder: 1,
        featured: true,
        isActive: true,
        createdAt: new Date('2024-01-01'),
        updatedAt: new Date(),
      },
      {
        id: 'srv_2',
        title: 'Next.js & React Frontend Engineering',
        slug: 'nextjs-react-frontend-engineering',
        icon: 'Globe',
        shortDescription: 'High-performance, pixel-perfect frontend experiences featuring polished animations, modern CSS, and optimal Core Web Vitals.',
        fullDescription: 'I engineer fast, fluid, and accessible frontends that captivate users and convert visitors. Utilizing Next.js App Router, Tailwind CSS, and Framer Motion, I deliver sub-second load times, excellent SEO scores, and delightful micro-interactions.',
        features: [
          'App Router implementation with Server Components and dynamic streaming',
          'Performance audit and optimization for 95+ Google Lighthouse scores',
          'Custom design system and reusable component library creation',
          'Fully responsive layouts with dark/light theme switching'
        ],
        technologies: ['Next.js', 'React 19', 'Tailwind CSS', 'Framer Motion', 'TypeScript'],
        displayOrder: 2,
        featured: true,
        isActive: true,
        createdAt: new Date('2024-01-01'),
        updatedAt: new Date(),
      },
      {
        id: 'srv_3',
        title: 'API Architecture, Microservices & Database Design',
        slug: 'api-architecture-database-design',
        icon: 'Cpu',
        shortDescription: 'Scalable backend services, high-throughput REST APIs, database normalization, and secure authentication.',
        fullDescription: 'Design and implementation of secure, resilient backend systems that handle heavy traffic effortlessly. I build structured REST APIs, integrate third-party payment gateways, optimize PostgreSQL queries, and implement robust JWT/OAuth security middleware.',
        features: [
          'Normalized PostgreSQL database architecture with indexing optimization',
          'Stateless JWT session authentication with role-based access control',
          'Comprehensive Zod request payload validation and sanitization',
          'OpenAPI/Swagger documentation generation for team clarity'
        ],
        technologies: ['Node.js', 'Express', 'PostgreSQL', 'Prisma', 'Redis', 'Docker'],
        displayOrder: 3,
        featured: true,
        isActive: true,
        createdAt: new Date('2024-01-01'),
        updatedAt: new Date(),
      },
      {
        id: 'srv_4',
        title: 'Cloud Deployment, Docker & DevOps Automation',
        slug: 'cloud-deployment-docker-devops',
        icon: 'Box',
        shortDescription: 'Multi-stage Docker containerization, CI/CD automated deployment pipelines, and cloud hosting architecture.',
        fullDescription: 'Eliminate "works on my machine" friction. I containerize your applications with lean multi-stage Docker builds, establish automated continuous integration workflows, configure SSL certificates, and deploy reliable cloud hosting environments.',
        features: [
          'Production-ready Docker and Docker Compose multi-service configurations',
          'GitHub Actions pipelines for automated testing, linting, and deployment',
          'Environment isolation across development, staging, and production',
          'Health checks, container logging, and automated restarts'
        ],
        technologies: ['Docker', 'Docker Compose', 'AWS', 'GitHub Actions', 'Linux', 'Nginx'],
        displayOrder: 4,
        featured: false,
        isActive: true,
        createdAt: new Date('2024-01-01'),
        updatedAt: new Date(),
      }
    ],
    careerOpportunities: [
      {
        id: 'car_amazon',
        companyName: 'Amazon',
        companyLogo: 'https://images.unsplash.com/photo-1523474253246-77884814d339?auto=format&fit=crop&w=120&q=80',
        jobTitle: 'Software Development Engineer II (AWS / Distributed Systems)',
        location: 'Seattle, WA / Remote (US)',
        country: 'United States',
        remoteType: 'Hybrid',
        employmentType: 'Full-time',
        jobDescription: 'Amazon Web Services is hiring engineers to build highly available distributed cloud infrastructure, microservices, and high-throughput developer tooling.',
        requiredSkills: ['AWS', 'Java', 'TypeScript', 'Distributed Systems', 'Docker', 'PostgreSQL'],
        salaryRange: '$165,000 - $230,000 USD + RSUs',
        jobUrl: 'https://amazon.com/career',
        careerUrl: 'https://amazon.com/career',
        applicationUrl: 'https://amazon.jobs',
        companyWebsite: 'https://amazon.com',
        postedDate: new Date('2024-03-01'),
        closingDate: null,
        status: 'Open',
        featured: true,
        displayOrder: 1,
        createdAt: new Date('2024-03-01'),
        updatedAt: new Date(),
      },
      {
        id: 'car_1',
        companyName: 'Stripe',
        companyLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=120&q=80',
        jobTitle: 'Staff Full-Stack Engineer - Billing Platform',
        location: 'San Francisco, CA / Seattle, WA',
        country: 'United States',
        remoteType: 'Remote',
        employmentType: 'Full-time',
        jobDescription: 'Stripe is looking for a Staff Full-Stack Engineer to architect the next generation of global subscription billing, merchant invoicing, and cross-border payment interfaces. Looking for strong expertise in TypeScript, React, distributed systems, and API design.',
        requiredSkills: ['TypeScript', 'React', 'Node.js', 'Distributed Systems', 'API Design'],
        salaryRange: '$220,000 - $285,000 USD + Equity',
        jobUrl: 'https://stripe.com/jobs',
        careerUrl: 'https://stripe.com/jobs',
        applicationUrl: 'https://stripe.com/jobs/staff-fullstack-engineer',
        companyWebsite: 'https://stripe.com',
        postedDate: new Date('2024-02-15'),
        closingDate: null,
        status: 'Open',
        featured: true,
        displayOrder: 2,
        createdAt: new Date('2024-02-15'),
        updatedAt: new Date(),
      },
      {
        id: 'car_2',
        companyName: 'Vercel',
        companyLogo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=120&q=80',
        jobTitle: 'Senior Full-Stack Engineer - Edge & Frameworks',
        location: 'Global Remote',
        country: 'Worldwide',
        remoteType: 'Remote',
        employmentType: 'Full-time',
        jobDescription: 'Join Vercel to evolve Next.js and frontend infrastructure. Work alongside the core team driving React Server Components, Edge middleware, and developer workflow tools used by millions of developers worldwide.',
        requiredSkills: ['Next.js', 'React', 'TypeScript', 'Edge Compute', 'Tailwind CSS'],
        salaryRange: '$180,000 - $240,000 USD + Equity',
        jobUrl: 'https://vercel.com/careers',
        careerUrl: 'https://vercel.com/careers',
        applicationUrl: 'https://vercel.com/careers/senior-fullstack',
        companyWebsite: 'https://vercel.com',
        postedDate: new Date('2024-02-20'),
        closingDate: null,
        status: 'Open',
        featured: true,
        displayOrder: 3,
        createdAt: new Date('2024-02-20'),
        updatedAt: new Date(),
      },
      {
        id: 'car_3',
        companyName: 'Datadog',
        companyLogo: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=120&q=80',
        jobTitle: 'Lead Software Engineer - Observability Dashboards',
        location: 'New York, NY',
        country: 'United States',
        remoteType: 'Hybrid',
        employmentType: 'Full-time',
        jobDescription: 'Build high-performance real-time data visualization consoles handling tens of millions of concurrent metrics. Looking for a developer with deep experience in WebGL/Canvas, React, Node.js, and low-latency APIs.',
        requiredSkills: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'Data Visualization'],
        salaryRange: '$200,000 - $260,000 USD',
        jobUrl: 'https://datadoghq.com/careers',
        careerUrl: 'https://datadoghq.com/careers',
        applicationUrl: 'https://datadoghq.com/careers/lead-engineer',
        companyWebsite: 'https://datadoghq.com',
        postedDate: new Date('2024-02-25'),
        closingDate: null,
        status: 'Open',
        featured: false,
        displayOrder: 4,
        createdAt: new Date('2024-02-25'),
        updatedAt: new Date(),
      }
    ],
    certifications: [
      {
        id: 'cert_1',
        title: 'AWS Certified Solutions Architect - Professional',
        issuingOrganization: 'Amazon Web Services (AWS)',
        organizationLogo: 'https://images.unsplash.com/photo-1607799279861-4dd421887fb3?auto=format&fit=crop&w=120&q=80',
        issueDate: new Date('2023-05-15'),
        expirationDate: new Date('2026-05-15'),
        credentialId: 'AWS-SAP-892144',
        credentialUrl: 'https://aws.amazon.com/verification',
        certificateImage: 'https://images.unsplash.com/photo-1607799279861-4dd421887fb3?auto=format&fit=crop&w=600&q=80',
        description: 'Advanced validation of comprehensive enterprise cloud architecture, high availability, disaster recovery, and multi-tier security design.',
        displayOrder: 1,
        createdAt: new Date('2023-05-15'),
        updatedAt: new Date(),
      },
      {
        id: 'cert_2',
        title: 'Certified Kubernetes Administrator (CKA)',
        issuingOrganization: 'The Linux Foundation / CNCF',
        organizationLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=120&q=80',
        issueDate: new Date('2022-09-10'),
        expirationDate: new Date('2025-09-10'),
        credentialId: 'CKA-2200-9831',
        credentialUrl: 'https://www.cncf.io/certification/cka/',
        certificateImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
        description: 'Demonstrated proficiency in Kubernetes cluster installation, networking, persistent storage, security policies, and live troubleshooting.',
        displayOrder: 2,
        createdAt: new Date('2022-09-10'),
        updatedAt: new Date(),
      },
      {
        id: 'cert_3',
        title: 'Meta Certified Front-End Developer',
        issuingOrganization: 'Meta',
        organizationLogo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=120&q=80',
        issueDate: new Date('2021-11-20'),
        expirationDate: null,
        credentialId: 'META-FE-55421',
        credentialUrl: 'https://coursera.org/verify/professional-cert/meta-frontend',
        certificateImage: null,
        description: 'In-depth mastery of modern React, advanced JavaScript, UX/UI principles, accessibility, and automated frontend testing suites.',
        displayOrder: 3,
        createdAt: new Date('2021-11-20'),
        updatedAt: new Date(),
      }
    ],
    achievements: [
      {
        id: 'ach_1',
        title: '1st Place Winner - Global FinTech Hackathon 2023',
        description: 'Led a 4-person engineering team to win first place out of 250+ teams by building an open-source decentralized micro-lending API with automated fraud protection.',
        icon: 'Trophy',
        image: 'https://images.unsplash.com/photo-1579389083078-4e7018379f7e?auto=format&fit=crop&w=600&q=80',
        date: new Date('2023-10-15'),
        organization: 'FinTech Innovation Alliance',
        url: 'https://example.com/hackathon-winner',
        displayOrder: 1,
        featured: true,
        createdAt: new Date('2023-10-15'),
        updatedAt: new Date(),
      },
      {
        id: 'ach_2',
        title: 'Keynote Speaker - Node+JS Global Summit 2024',
        description: 'Delivered an in-depth technical talk on "Architecting Resilient Event Loops & Streams in High-Throughput Node.js Microservices" to an audience of 1,200+ developers.',
        icon: 'Award',
        image: null,
        date: new Date('2024-01-20'),
        organization: 'OpenJS Foundation',
        url: 'https://example.com/speaker-deck',
        displayOrder: 2,
        featured: true,
        createdAt: new Date('2024-01-20'),
        updatedAt: new Date(),
      },
      {
        id: 'ach_3',
        title: 'Open Source Maintainer - 1.5M+ Downloads',
        description: 'Creator and active maintainer of popular TypeScript validation and state synchronization utilities adopted across hundreds of production codebases.',
        icon: 'Star',
        image: null,
        date: new Date('2023-01-01'),
        organization: 'GitHub Open Source',
        url: 'https://github.com',
        displayOrder: 3,
        featured: false,
        createdAt: new Date('2023-01-01'),
        updatedAt: new Date(),
      }
    ],
    testimonials: [
      {
        id: 'tst_1',
        name: 'Sarah Jenkins',
        designation: 'VP of Engineering',
        company: 'CloudScale Technologies',
        profileImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
        testimonial: 'Alex is an extraordinary engineering talent. He possesses that rare combination of deep architectural acumen on the backend and obsessive attention to pixel-perfection and performance on the frontend. Under his leadership, our platform latency dropped by over 70%.',
        rating: 5,
        date: new Date('2023-12-10'),
        featured: true,
        displayOrder: 1,
        createdAt: new Date('2023-12-10'),
        updatedAt: new Date(),
      },
      {
        id: 'tst_2',
        name: 'Marcus Chen',
        designation: 'Chief Technology Officer',
        company: 'Apex FinTech Systems',
        profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
        testimonial: 'In over 15 years in financial software, Alex is among the top 1% of engineers I have worked with. His work on our double-entry ledger was mathematically flawless and delivered ahead of our strict regulatory deadline.',
        rating: 5,
        date: new Date('2022-04-18'),
        featured: true,
        displayOrder: 2,
        createdAt: new Date('2022-04-18'),
        updatedAt: new Date(),
      },
      {
        id: 'tst_3',
        name: 'Elena Rostova',
        designation: 'Product Director',
        company: 'Nova Interactive Labs',
        profileImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
        testimonial: 'Alex communicates with extreme clarity, writes maintainable self-documenting code, and understands business outcomes just as well as technical trade-offs. Any engineering team would be immensely fortunate to have him.',
        rating: 5,
        date: new Date('2020-02-14'),
        featured: true,
        displayOrder: 3,
        createdAt: new Date('2020-02-14'),
        updatedAt: new Date(),
      }
    ],
    socialLinks: [
      { id: 'soc_1', platform: 'GitHub', url: 'https://github.com', icon: 'Github', isActive: true, displayOrder: 1 },
      { id: 'soc_2', platform: 'LinkedIn', url: 'https://linkedin.com', icon: 'Linkedin', isActive: true, displayOrder: 2 },
      { id: 'soc_3', platform: 'Twitter/X', url: 'https://twitter.com', icon: 'Twitter', isActive: true, displayOrder: 3 },
      { id: 'soc_4', platform: 'Dev.to', url: 'https://dev.to', icon: 'BookOpen', isActive: true, displayOrder: 4 },
      { id: 'soc_5', platform: 'Medium', url: 'https://medium.com', icon: 'FileText', isActive: true, displayOrder: 5 },
    ],
    websiteSettings: [
      { id: 'set_1', key: 'siteName', value: 'Debkanta Dey | Senior Full-Stack Engineer', description: 'Website title displayed in browser tab and hero' },
      { id: 'set_2', key: 'primaryColor', value: '#0B1F3A', description: 'Primary brand color (Navy Blue)' },
      { id: 'set_3', key: 'accentColor', value: '#22D3EE', description: 'Accent color (Electric Cyan / Teal)' },
      { id: 'set_4', key: 'contactEmail', value: 'alex@alexmorgan.dev', description: 'Official email address for contact routing' },
      { id: 'set_5', key: 'contactPhone', value: '+1 (415) 890-4211', description: 'Official contact phone number' },
      { id: 'set_6', key: 'location', value: 'San Francisco, CA (Open to Worldwide Remote)', description: 'Developer base location' },
      { id: 'set_7', key: 'footerCopyright', value: '© 2026 Debkanta Dey. Built with Next.js, Node.js & PostgreSQL.', description: 'Footer copyright note' },
      { id: 'set_8', key: 'maintenanceMode', value: 'false', description: 'Set to true to activate maintenance screen' },
      { id: 'set_9', key: 'googleAnalyticsId', value: '', description: 'Optional GA4 Measurement ID' }
    ]
  };
};
